matrix:
  allow_failures:
    - os: windows

os:
  - linux
  - osx
  - windows

language: node_js

node_js:
  - node

cache:
  - npm: true
  - cargo: true

before_install:
  # Install Rust and Cargo
  - |
    if [ "$TRAVIS_OS_NAME" == "windows" ]; then
      choco install rust
    else
      curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs > /tmp/rustup.sh && /
      sh /tmp/rustup.sh -y && /
      export PATH="$HOME/.cargo/bin:$PATH" && /
      source "$HOME/.cargo/env"
    fi
  # Install global NPM packages
  - node -v
  - npm -v
  - npm install

script:
  # Publish when using '[publish binary]' keywords
  - COMMIT_MESSAGE=$(git log --format=%B --no-merges -n 1 | tr -d '\n')
  - if [[ ${COMMIT_MESSAGE} =~ "[publish binary]" ]]; then npm run upload-binary || exit 0; fi;
